[PHP]
extension_dir="ext"
date.timezone="Asia/Manila"
memory_limit=512M
post_max_size=32M
upload_max_filesize=32M
max_execution_time=120
default_socket_timeout=60
openssl.cafile="C:\Users\Lorraine\Desktop\cafe\tools\php\cacert.pem"
curl.cainfo="C:\Users\Lorraine\Desktop\cafe\tools\php\cacert.pem"

extension=curl
extension=fileinfo
extension=mbstring
extension=openssl
extension=pdo_pgsql
extension=pdo_sqlite
extension=pgsql
extension=sodium
extension=sqlite3
extension=zip
